---
name: "JellyPy"
guid: "a5bd541f-38dc-467e-9a9a-15fe3f3bcf5c"
version: "2.1.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Automatically manage Sonarr & Radarr monitoring based on your Jellyfin watch activity."
description: >
  JellyPy automatically manages your Sonarr and Radarr monitoring based on what you watch in Jellyfin.

  Native Sonarr Integration:
  - Automatically monitors next N episodes after watching
  - Smart episode buffer management with configurable minimum unwatched queue
  - Season-by-season monitoring control
  - Unmonitor watched episodes to reduce clutter
  - Automatic search triggering for newly monitored content

  Native Radarr Integration:
  - Automatically unmonitor movies after watching
  - Percentage-based watch detection (configurable threshold)
  - Quality cutoff checking to prevent premature unmonitoring
  - Keep movies monitored if upgrades are still possible

  Legacy Features:
  - Execute custom Python scripts on Jellyfin events (PlaybackStart, PlaybackStop, etc.)
  - Flexible conditional execution based on media properties
  - Custom environment variables and data attributes

  Perfect for maintaining an organized, automated download workflow without manual intervention.
category: "Notifications"
owner: "caleb-venner"
artifacts:
- "Jellyfin.Plugin.JellyPy.dll"
changelog: >
  ### Version 1.1.1

  **Patch Release - Optimized Package Size**

  - **Reduced download size** from ~8MB to ~300KB
  - **Removed unnecessary dependencies** - only includes plugin-specific files
  - **Server-based API key encryption** using Jellyfin SystemId for enhanced security
  - **Test connection functionality** for Sonarr and Radarr with real-time validation
  - **System-independent encryption** that survives OS updates and machine changes
  - **Clean implementation** with legacy fallback code removed

  **Security Improvements:**
  - AES-256-CBC encryption with PBKDF2 key derivation (10,000 iterations)
  - Three-component key generation: Plugin GUID + Server ID + Static Salt
  - Automatic encryption of API keys on save
  - Enhanced documentation with comprehensive security guidance

  **Note:** This patch release provides the same security features as v1.1.0 with an optimized, minimal package size.

