---
name: "Jellypy"
guid: "a5bd541f-38dc-467e-9a9a-15fe3f3bcf5c"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Execute python scripts from notifications events."
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "Caleb"
artifacts:
- "Jellyfin.Plugin.Jellypy.dll"
changelog: >
  changelog
